### ISSUE TITLE
7.16.0 does not include the default icons

### ISSUE THREAD

**Issue by ericcirone** [dderevjanik/github-vscode-icons#1]
All icons with the prefix "default" are missing from 7.16.0.

**Comment by dderevjanik** [comment]
Hi,

thanks for filing issue, but I'm not sure what you mean that icons with prefix "default" are missing. 
Can you explain it a little bit more, please ? 
This repository is only [chrome extension](https://chrome.google.com/webstore/detail/github-vscode-icons/hoccpcefjcgnabbmojbfoflggkecmpgd) which displays [vscode-icons](https://github.com/vscode-icons/vscode-icons) on GH repos. So, it is possible that you wanted to create issue for [vscode-icons](https://github.com/vscode-icons/vscode-icons)

**Comment by ericcirone** [comment]
@dderevjanik Ahh sorry i think got the wrong repo. Sorry about that.
