### ISSUE TITLE
Include extension Totvs

### ISSUE THREAD

**Issue by efdeiasoliveira** [dderevjanik/github-vscode-icons#10]
Please include TOTVS Protheus prw, prg, prx and tlpp extension. Follow attached files.
[ICONS TOTVS.zip](https://github.com/dderevjanik/github-vscode-icons/files/3566896/ICONS.TOTVS.zip)

**Comment by dderevjanik** [comment]
Hi,
this extension is using vscode-icons repo
If you want to propose new icon to vscode-icons, please create an issue in [vscode-icons](https://github.com/vscode-icons/vscode-icons/) repo. When a new version come out, I'll try to include those changes to this project.

**Comment by efdeiasoliveira** [comment]
Ok, Thank You!
