### ISSUE TITLE
Broken on rollup-plugin-vue repo

### ISSUE THREAD

**Issue by gluons** [dderevjanik/github-vscode-icons#11]
Broken on [vuejs/rollup-plugin-vue](https://github.com/vuejs/rollup-plugin-vue).

**Browser:** Firefox Developer 72.0b11
**OS:** Windows 10

![ภาพ](https://user-images.githubusercontent.com/4688092/71861630-91566580-3129-11ea-8a5a-a71ca22b22f0.png)

**Comment by dderevjanik** [comment]
Hi,

thank you for creating an issue and sorry for late reply. I finally managed to fix this bug. 
Update will be available in next few hours.

![image](https://user-images.githubusercontent.com/4524497/75151908-16acce00-5708-11ea-8bc1-0b23a46636d8.png)

**Comment by gluons** [comment]
It's fixed. Thank you very much.  
I close this issue now.

![ภาพ](https://user-images.githubusercontent.com/4688092/75353808-92607380-58de-11ea-989c-92073b7a81a2.png)
