### ISSUE TITLE
Extension not work

### ISSUE THREAD

**Issue by fakhamatia** [dderevjanik/github-vscode-icons#13]
![ksnip_20200224-141429](https://user-images.githubusercontent.com/20030910/75146385-38aa4e80-5710-11ea-90fc-d8a8df080cb5.png)

![ksnip_20200224-141451](https://user-images.githubusercontent.com/20030910/75146390-3ba53f00-5710-11ea-9e33-fa9fd569e9c6.png)

**Comment by dderevjanik** [comment]
Hi, 

thank you very much for creating an issue. Sadly, Github changed html markup. 
There's is already PR #12 , but I need also update css because icons are smaller now. 

Expect fix very soon :)

**Comment by fakhamatia** [comment]
Thank you,
What about GitLab? second image

**Comment by dderevjanik** [comment]
Will try to fix ti also, but GitLab is pretty problematic

**Comment by s-weigand** [comment]
Just wanted to let you know, that the extension still works on `GitLab Community Edition 10.4.7`.
If it is a selector problem again, maybe use an if structure, checking the length of the found elements.

**Comment by dderevjanik** [comment]
That's really good idea, will try it that way. Is there any way to check difference between community and enterprise edition of repo structure ? 

BTW, extension current status
![image](https://user-images.githubusercontent.com/4524497/75192106-e5f28600-5753-11ea-8caf-ba5f5c94df53.png)

**Comment by s-weigand** [comment]
>  Is there any way to check difference between community and enterprise edition of repo structure ?

Looks like it is `just` a difference in features, mainly pipelines I guess.
> For both versions: All javascript code in GitLab is open source. All javascript code written by GitLab is under the same MIT license. 

[see](https://about.gitlab.com/install/ce-or-ee/)

**Comment by dderevjanik** [comment]
I see, but I don't know what's difference in html repo structure.
Do you have any examples ? 

*Note: extension still in review process :( *

**Comment by KROSF** [comment]
Working again 😃

**Comment by dderevjanik** [comment]
Finally, but I created an Issue for further changes https://github.com/dderevjanik/github-vscode-icons/issues/16 - what do you think ?

**Comment by antoinerousseau** [comment]
I'm using an up to date version of the extension and I'm having this issue too, did it break again?

**Comment by s-weigand** [comment]
@antoinerousseau I also have an issue, but it appears to be some kind of race condition. 
Combinations of refreshing the page (`F5` and `Ctrl`+`F5`) make it work. Could you try to confirm this, behaviour?

**Comment by gencer** [comment]
Aha! I was thinking something is wrong with my environment but i,t seems it is generic.

When page loads most of the time, icon loader shown. No custom icons present. After pressing F5 (or few times) then icons get loaded successfully.

Most of the time it looks like this:

![image](https://user-images.githubusercontent.com/1711576/80206041-56befd00-8634-11ea-8547-5ef2afab3901.png)


Please note that, even if icons work perfectly, If you press F5 few times, it is possible to see loader + default icons again. So this doesn't mean icons are broken on first load. You can achieve same error by pressing F5 few times.

**Comment by antoinerousseau** [comment]
Yes I confirm it's a race condition, it happens randomly on first load or on reloading/force reloading

**Comment by Rabattkarte** [comment]
I am observing the same issue.

**Comment by s-weigand** [comment]
I attempted a fix in #20 and uploaded the built extensions as zip there. Feel free to test it, maybe it could help @dderevjanik with the review. Or at least he has to review less if you find a problem first ^^

**Comment by KROSF** [comment]
@s-weigand I installed the zip and works fine.
