### ISSUE TITLE
icons perpetually load on first page load in chromium

### ISSUE THREAD

**Issue by michaelgosling** [dderevjanik/github-vscode-icons#17]
I'm thinking its related to refined github, but i cant understand why a refresh fixes it.

![github-icons](https://user-images.githubusercontent.com/28716158/79497095-8438f480-7ffd-11ea-9a3c-3ef2324ad978.png)
after refresh:
![github-icons-2](https://user-images.githubusercontent.com/28716158/79497114-8ac76c00-7ffd-11ea-9603-013a42ab7067.png)

this is in Edge, btw, but it should be the same as chromium.

**Comment by THPubs** [comment]
I can confirm that the same thing is happening in Firefox. I'm using Firefox Developer Edition.

**Comment by s-weigand** [comment]
I attempted a fix in #20 and uploaded the built extensions as zip there. Feel free to test it, maybe it could help @dderevjanik with the review. Or at least he has to review less if you find a problem first ^^

**Comment by laedit** [comment]
@s-weigand I just tested it and all seems fine, thanks! :)

**Comment by psygo** [comment]
@THPubs I'm using regular Firefox and it's the same thing here.

**Comment by dderevjanik** [comment]
This should be fixed #22, closing for now
