### ISSUE TITLE
Doesn't work on new GitHub Design

### ISSUE THREAD

**Issue by kyle-seongwoo-jun** [dderevjanik/github-vscode-icons#21]
![image](https://user-images.githubusercontent.com/16515307/85241311-59906f80-b476-11ea-8455-a24e81713695.png)

**Comment by gluons** [comment]
I face this problem too. GitHub new design is now released for everyone.  
Can't back to old design anymore.

**Comment by dderevjanik** [comment]
Hi,
thank you for creating an issue. There's possible fix for this issue [#23](https://github.com/dderevjanik/github-vscode-icons/pull/23)

**Comment by kyle-seongwoo-jun** [comment]
@dderevjanik Great!
