### ISSUE TITLE
vertical-align

### ISSUE THREAD

**Issue by antoinerousseau** [dderevjanik/github-vscode-icons#28]
Icons are not properly aligned vertically in GitHub.
I suggest adding `vertical-align: -3px;` to the `<img>` tags.

default | + github-vscode-icons | + vertical-align
-------|------------------------|----------------
<img width="210" alt="Capture d’écran 2020-08-26 à 12 30 52" src="https://user-images.githubusercontent.com/160279/91293241-03062100-e798-11ea-94ec-2541699a1dba.png"> | <img width="212" alt="Capture d’écran 2020-08-26 à 12 29 52" src="https://user-images.githubusercontent.com/160279/91293256-08636b80-e798-11ea-901c-1007fc2e6a62.png"> | <img width="204" alt="Capture d’écran 2020-08-26 à 12 34 25" src="https://user-images.githubusercontent.com/160279/91293588-8c1d5800-e798-11ea-85d3-172512c6e126.png">

What do you think?

**Comment by antoinerousseau** [comment]
cc @dderevjanik @s-weigand

**Comment by s-weigand** [comment]
Yeah IMHO that looks better and I also like that it shrinks the overall size.

**Comment by antoinerousseau** [comment]
Cool. Is there a common CSS or style file I can edit? Otherwise can you point me to the file(s) to edit if I want to make a PR?

**Comment by s-weigand** [comment]
[This is the css file used by the extension.](https://github.com/dderevjanik/github-vscode-icons/blob/master/build/content.css)

**Comment by s-weigand** [comment]
Since `vertical-align: middle;` looks pretty similar, adding the class `vscode-icon` to the `img` should do the trick as well.

This would mean just adding `class="vscode-icon"` to this line.

https://github.com/dderevjanik/github-vscode-icons/blob/3470130cbd55f0470cda9491e34325e3e0e5a55c/packages/content/pages/GitHub.ts#L103

Try it out and tell me what you think:
```javascript
document.querySelectorAll("div.Box-row > div:nth-child(1) > img").forEach((item)=>{item.setAttribute('class', 'vscode-icon');})
```

**Comment by antoinerousseau** [comment]
@s-weigand how about this: #30
