### ISSUE TITLE
Can't view icons on private instance of GitLab :(

### ISSUE THREAD

**Issue by TeeSeal** [dderevjanik/github-vscode-icons#3]
My company uses a private instance of GitLab to host our code and the extension doesn't seem to work there, I just get an infinite spinner like this:

![image](https://user-images.githubusercontent.com/14080148/41536848-6ec2cdbc-730f-11e8-8adb-5ebba788912a.png)

It works fine on the regular GitLab page! Is there anything I can tweak in order to get it working on our private instance of GitLab? Or at the very least, disable the extension on that specific domain?

Here's what the HTML looks like:
```html
<td class="tree-item-file-name">
  <i aria-hidden="true" data-hidden="true" class="fa fa-folder fa-fw"></i>
  <a class="str-truncated" title="bin" href="/***/***/tree/master/bin"><span>bin</span></a>
</td>
```

**Comment by dderevjanik** [comment]
Hi,

thank you for creating an issue :) .

I'm not exactly sure what is happening on your host. Currently supported hosts are defined in  https://github.com/dderevjanik/github-vscode-icons/blob/master/build/manifest.json#L43

It seems that you have different host than defined in `manifest`, nevertheless, css/js are still loaded. This is probably a bug. 
I'm going to fix it :)

**Comment by TeeSeal** [comment]
Hey @dderevjanik,

Thanks for the swift reply.
Our host has an address of the form: `https://git.<company-name>.com`, if that would help track down the issue.

**Comment by dderevjanik** [comment]
Sure,
this is helpful information :) . Thank you

**Comment by dderevjanik** [comment]
@TeeSeal , sorry for late response, but I'm having a hard time to figuring it how to solve this issue, because:

- Your company have different gitlab version and I don't know which one
- It will take too much time to support all gitlab version, test them and support them

What do you think about providing a settings to disable extension on specific hostings ?

**Comment by TeeSeal** [comment]
@dderevjanik Don't worry about it.

That is perfectly fine! it was one of my suggestions to begin with.

**Comment by ZanderBrown** [comment]
Perhaps have an at-own-risk option for adding additional hosts?

Personally I'd like to have this on gitlab.gnome.org
