### ISSUE TITLE
publish to Mozilla add ons

### ISSUE THREAD

**Issue by steebchen** [dderevjanik/github-vscode-icons#4]
Should be easy to publish as everything works as in chrome.

**Comment by dderevjanik** [comment]
Hi,
thank you for submitting an issue.

I'm not a firefox user, so I had a quite hard time to test it properly. 
Are you firefox user ? It would be great to test this extension properly before releasing it. 

Here is test version, please, test it if you can 
https://addons.mozilla.org/en-GB/firefox/addon/github-vscode-icons/

Thanks

**Comment by steebchen** [comment]
Thanks, awesome! Yes, Firefox is my browser of choice. I just installed it and everything works fine. What exactly do you mean by "testing properly"? I clicked around a lot, including subfolders, different repos on Github and it seems fine. In don't know about Bitbucket or Gitlab, though.

**Comment by jens1o** [comment]
I can confirm the extension is working fine with Firefox :)

Where's the sourcecode for the Firefox Extension?

**Comment by dderevjanik** [comment]
@steebchen `testing properly` I mean testing it for several days and looking into console to see if there are errors :D .

@jens1o sorcecode is this repo with [latest commit](https://github.com/dderevjanik/github-vscode-icons/commit/3a81e8a9ae5eae7310f757b6ed359c285dfd9a7d). You can see that I added a script for building a `manifest.json` for firefox.

**Comment by steebchen** [comment]
Just wanted to let you know that I didn't see any issues so far (and I use Github a lot).

**Comment by dderevjanik** [comment]
Thank you very much for feedback ! :)

I updated `README.md` with a link to download mozilla extension.

**Comment by steebchen** [comment]
I was just going to report this bug:

![selection_999 047](https://user-images.githubusercontent.com/5013932/45459014-b8985080-b6f6-11e8-96af-df20cacc7347.jpg)

I tried a re-install of the plugin and everything works fine again, maybe this is related to 9db4a48cd86cbb7a4fc503ef0a4695d254389ba6?

**Comment by dderevjanik** [comment]
is it working now ? 
I submitted fix yesterday and it takes several hours to update all users extension

**Comment by steebchen** [comment]
Yep, it's working!
