### ISSUE TITLE
Icons do not load anymore due to CSP

### ISSUE THREAD

**Issue by nesl247** [dderevjanik/github-vscode-icons#5]
Looks like this doesn't work anymore due to a change GitHub has made.

![image](https://user-images.githubusercontent.com/1037526/45433044-56e5d100-b679-11e8-9f73-e20ca31cc15a.png)

**Comment by dderevjanik** [comment]
Hi,

thank you very much for reporting a bug. New GH update changed classname of one div. 
I submitted fixed version of extension to both chrome and firefox store. 

Your extension will be updated in next few hours. 

Sorry for troubles

**Comment by nesl247** [comment]
Thanks! Updated Chrome manually.
