### ISSUE TITLE
vscode icons for files are no longer loaded in latest chrome

### ISSUE THREAD

**Issue by gencer** [dderevjanik/github-vscode-icons#8]
On latest Chrome, folder icons are applied, however, file icons look like this.

![image](https://user-images.githubusercontent.com/1711576/56726822-3118c280-6758-11e9-84f8-05aa8fc49e96.png)

This behavior also valid for GitLab too. Folders are visible, file icons are not.

I catch this error in console:

```
content.js:1 Uncaught (in promise) TypeError: Cannot read property 'includes' of undefined
    at content.js:1
    at y (content.js:1)
    at Object.t.initGithub [as github] (content.js:1)
    at Object.t.showIconsForHosting (content.js:1)
    at content.js:1
    at Generator.next (<anonymous>)
    at p (content.js:1)
(anonymous) @ content.js:1
y @ content.js:1
t.initGithub @ content.js:1
t.showIconsForHosting @ content.js:1
(anonymous) @ content.js:1
p @ content.js:1
Promise.then (async)
g @ content.js:1
(anonymous) @ content.js:1
l @ content.js:1
(anonymous) @ content.js:1
(anonymous) @ content.js:1
s @ content.js:1
(anonymous) @ content.js:1
(anonymous) @ content.js:1
```

**Comment by dderevjanik** [comment]
Hi,
thanks for creating an issue. I tried it on several machines, probably you have different GH version or github-vscode-icons is intercepted by other extension in your chrome.

Which version of chrome are you using ?

Do you have any other chrome extension that are changing how GH repo tree looks like (manipulating with DOM) ?

**Comment by steebchen** [comment]
Same issue on latest Firefox on Linux:

Sometimes, the folder icons are showing:
![Selection_999(1219)](https://user-images.githubusercontent.com/5013932/56730474-62918e00-6758-11e9-986c-84bb1984fb77.jpg)

Most times, no icons are loading at all though:
![Selection_999(1220)](https://user-images.githubusercontent.com/5013932/56730469-602f3400-6758-11e9-805b-689c613af858.jpg)

**Comment by steebchen** [comment]
In my case, I think it's because of the extension [refined github](https://github.com/sindresorhus/refined-github). When I disable this extension everything works. However, this was just happening for some days/weeks (was on vacation so I'm not sure) – I was using refined github with vscode icons before and everything worked fine until recently.

**Comment by dderevjanik** [comment]
Ok, thank you very much for details. It looks like refined github is manipulating with DOM and that causes errors.

Will try fix it ASAP :)

**Comment by gencer** [comment]
Ah! yes, I have refined github too.

**Comment by Rud156** [comment]
I'm too having the same issue and yeah, I also have Refined Github installed

**Comment by dderevjanik** [comment]
I published new version with fixed issue to chrome store. You can expect that extension will be updated in next few hours :)

**Comment by gencer** [comment]
Thanks! Fixed on my end.

**Comment by Rud156** [comment]
I can also confirm that it is now working on my side.

**Comment by steebchen** [comment]
Can you also update the Firefox extension please @dderevjanik?

**Comment by dderevjanik** [comment]
@steebchen thanks for mentioning firefox, I totally forgot about it....

I submited new version in firefox dev, but it will take much more time (to be reviewed from firefox side) than in chrome store before it will be available for you :/

**Comment by steebchen** [comment]
It's published for a few days now by the way, thanks for fixing!

**Comment by gencer** [comment]
New refined github released and probably broke the component again.

**Comment by dderevjanik** [comment]
I tried newest version `19.5.18.1335` without any issues. 
Could you please post more details ?  Thanks :)

**Comment by gencer** [comment]
I see errors as below:

```
Denying load of <URL>. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
github-vscode-icons:1 Denying load of chrome-extension://hoccpcefjcgnabbmojbfoflggkecmpgd/icons/. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
github-vscode-icons:1 Denying load of chrome-extension://hoccpcefjcgnabbmojbfoflggkecmpgd/icons/. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
github-vscode-icons:1 Denying load of chrome-extension://hoccpcefjcgnabbmojbfoflggkecmpgd/icons/. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
```

**Comment by dderevjanik** [comment]
Is that repo public ? 
Don't have any idea which could cause that problem....

**Comment by gencer** [comment]
Yes it is public

**Comment by dderevjanik** [comment]
url, please :)

**Comment by gencer** [comment]
https://github.com/dderevjanik/github-vscode-icons

😂

All repos has this issue

screenshot:
![screencapture-github-dderevjanik-github-vscode-icons-2019-05-18-23_16_54](https://user-images.githubusercontent.com/1711576/57974578-1d612480-79c3-11e9-8e63-5bc3715d1e95.png)

**Comment by dderevjanik** [comment]
:D Well, everything looks Ok on my side....
Do you have any special options turned on in refined-github ext ? Which version are you using ? My version is `19.5.18.1335`

**Comment by gencer** [comment]
My version is `19.5.19.1547`. I enabled private access token (also tried without it).

I see error at top:

```
Refused to load the font 'data:application/font-woff2;base64,d09GMgABAAAAAQ5sABIAAAADuOQAAQ4EAAEAgwAAAAAAAAAAAAAAAAAAAAAAAAAAG4SpIhy4XhSHMgZgAJJmCF4JgnMREAqGskiFyggSgrVoATYCJAOdOAuOXgAEIAWPGAfGYAyDGFsKfLME/nOMvX+HnQoMqyRqK6tt2TW8K2BDX9Umu4PZkCXwtMjpcHYNTx6UUmu30UdwcxxnVMvcNgAim7rdXiPZ////////////C5dF2ObuXM7ZvQeSECARwueHlaLVtkJEIaLRAI3ulswSE13cSPdM15RCyYQuuS7A0mBqpQO9pYZWQQMqa9lQb0dpJzHxHpLyCHIi8uBdwF58nNH+YOA40OpJvEjJtaokKaUkx/N5UeSinp5TWoW1vSpFjimBgeFGeCF66U0n6ZUN/qSqC4XC11GKUNmzSy2d5Jxyqw5JzGUlJUnyi0lKkE8BlxadTZsyRm8c1/Cti2hEjzIH...FVw9csGnQ1BnbMbfzgRj3WjPytwZYWpPh3OtmsLZaNcxxqaGVqMVqFffFpU8bbs/0N1vG3POWfS7LUeB81TfHn+VbD7x/UnT3lXyFltHfdX6+X6Rzmg9d4dAISK7GlTj2zgME/JUwAETAECwABAUgUmAysrKI5shRwAchnFSMheQ8UoKlvnVbkW9mMeq2+bbO9EQ2q09Z9wzsADarYt4ftoamBDi8gmfbZKnl+lkZWyRx1VYVSIpVFXs9VXy9ytCyTNYt09YIAGKjqpDT22SgOdP5OsdAK/vOCXFnrpEwA/PPTJiopB7HxZV+MlaGCT/04K/LY3kjPYV/YR146Ggg+9sX6na/c2So+Epz3PXve3PKRylPIhNZASBUYVDIGhikiWc1jj/claeVCJvljX7JfvO+xhfTDIjSXBs4HV16Ol/BMfcuFQ4NRmDOWEh6diOI6NZmGl87N9J+r2JfpW2+5NhV/fGHLO57Yavbq7zaCewa/RDxp/aSH+luOPwAA' because it violates the following Content Security Policy directive: "font-src github.githubassets.com".
```

**Comment by Rud156** [comment]
@dderevjanik I too am facing the same issue.
The error is `Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700&amp;subset=cyrillic`.

This was working when initially when the fix for GithubRefined was updated. But now it stopped working from sometime yesterday.

**Comment by dderevjanik** [comment]
Guys, Thank you very much for your support and patience. 
Finally, I was able to reproduce error (I can only reproduce it in chromium, not in chrome). It seems refined-github changed placement of github svg icon again.

I published new version `1.19` to chrome store, so you can to expect working version in next few hours. 
I also added better error messaging (in console) and catching (unknown icons don't break whole repo).

**Comment by steebchen** [comment]
@dderevjanik Can you please also publish to the Firefox store? It seems refined github updated for me today and I have the same issue:

![Selection_150](https://user-images.githubusercontent.com/5013932/58024908-8ce62980-7b13-11e9-9db8-a51543d203ee.jpg)

**Comment by gencer** [comment]
Confirmed. Works here on Chrome.

Thanks!

**Comment by Rud156** [comment]
Confirmed. Works now on Vivaldi

**Comment by dderevjanik** [comment]
Thanks, 
closing closed Issue, for now :D 

@steebchen should be available for you in next few hours :)
