### ISSUE TITLE
`static` file has no icon and it causes other lines being larger than usual

### ISSUE THREAD

**Issue by gencer** [dderevjanik/github-vscode-icons#9]
There is an issue with a file without extension (called `static` in this case)

Due to icon not found, it causes icons  being larger than usual

Screenshot:

![image](https://user-images.githubusercontent.com/1711576/56956107-e29a6800-6b4b-11e9-944e-fe7b58315192.png)

**See**: https://github.com/getsentry/sentry

Using Chrome.

**Comment by dderevjanik** [comment]
Thanks, will fix it in next Few days.... 
still waiting for new version of vscode-icons to be released :)

**Comment by gencer** [comment]
@dderevjanik any news on this? Also new refined github released and probably broke the component again.

**Comment by dderevjanik** [comment]
Well, I tough that there will be new version of `vscode-icons`... I'm going to fix this issue with static file

**Comment by dderevjanik** [comment]
Fixed in `1.19`
